src/Angiris.CentralAdmin.WebApp/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RestSharp;
using RestSharp.Extensions;
using RestSharp.Validation;

namespace Angiris.CentralAdmin.WebApp.Controllers
{
    public class ApiController
    {
        private static readonly string _secretKey = "key-c71cc13573773b936e20883d961dcb84";

        public static IRestResponse SendEmail(string To, string From, string Body, string Subject)
        {
            RestClient client = new RestClient();
            client.BaseUrl = new Uri("https://api.mailgun.net/v2");
            client.Authenticator =
                    new HttpBasicAuthenticator("api",
                                               _secretKey);
            RestRequest request = new RestRequest();
            request.AddParameter("domain",
                                 "alephzero.cn", ParameterType.UrlSegment);
            request.Resource = "{domain}/messages";
            request.AddParameter("from", "No-Reply <no-reply@alephzero.cn>");
            request.AddParameter("to", To);
            request.AddParameter("subject", Subject);
            request.AddParameter("text", Body);
            request.AddParameter("o:tracking", true);
            request.Method = Method.POST;
            return client.Execute(request);
        }
    }
}

src/Angiris.CentralAdmin.WebApp/Controllers/ConsoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using Angiris.Core.Models;
using Newtonsoft.Json;
using Angiris.APIService.Core;

namespace Angiris.CentralAdmin.WebApp.Controllers
{
    public class ConsoleController : Controller
    {
        // GET: Console
        public ActionResult Index()
        {
            return View("FlightQuery");
        }

        public ActionResult FlightQuery()
        {
            return View();
        }

        /// <summary>
        /// Query via client redis api
        /// </summary>
        /// <param name="departure"></param>
        /// <param name="arrival"></param>
        /// <returns></returns>
        public async Task<ActionResult> ListDates(string departure, string arrival)
        {
            FlightQueryService querySvc = new FlightQueryService();
            var keys = await querySvc.QueryKeys(departure, arrival, null);

            var dates = keys.Select(k => k.Split('-').LastOrDefault()).OrderBy(t=>t).ToList();

            return Json(dates,JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Query via exposed API management
        /// </summary>
        /// <param name="departure"></param>
        /// <param name="arrival"></param>
        /// <param name="date"></param>
        /// <param name="company"></param>
        /// <returns></returns>
        [System.Web.Mvc.HttpPost]
        public async Task<ActionResult> _FlightQuery(string departure, string arrival, string date, string company = "")
        {
            // aaa-hhh-20150429
            //HttpClient httpClient = new HttpClient();
            //var apitoken = "73caed41790745e39d7fce419714980c";
            //string requestUrl =
            //    string.Format(
            //        "https://angirisdemo.azure-api.net/flights/query?departure={0}&arrival={1}&date={2}&company={3}&subscription-key={4}",
            //        departure, arrival, date, company, apitoken
            //        );
            //string response = await httpClient.GetStringAsync(requestUrl);
            //var responseData = JsonConvert.DeserializeObject<IEnumerable<FlightResponse>>(response);

            FlightQueryService querySvc = new FlightQueryService();

            DateTime flightDate;

            if (string.IsNullOrEmpty(departure) || string.IsNullOrEmpty(arrival)
                ||
                !(DateTime.TryParse(date, out flightDate) || DateTime.TryParseExact(date, "yyyyMMdd", null, System.Globalization.DateTimeStyles.None, out flightDate))
                )
                throw new HttpResponseException(HttpStatusCode.Forbidden);

            FlightRequest req = new FlightRequest() { DepartureCity = departure, ArrivalCity = arrival, FlightDate = flightDate, Company = company };

            var responseData =  await querySvc.QueryEntities(req);

            return PartialView("_FlightQueryResult",responseData);
        }

        
    }
}

src/Angiris.CentralAdmin.WebApp/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Angiris.CentralAdmin.Core;
using Angiris.Core.Models;

namespace Angiris.CentralAdmin.WebApp.Controllers
{
    public class DashboardController : Controller
    {
        readonly TelemetryService _svc = new TelemetryService();

        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DaemonStatus()
        {
            return View();
        }

        public ActionResult _DaemonStatusResult()
        {
            var telemetrydata = new List<DaemonStatus>();
            //await svc.GetAllDaemonStatusListAsync();
            Task.Run(async () =>
            {
                telemetrydata = await _svc.GetAllDaemonStatusListAsync();
            }).Wait();

            //TODO: understand why the behaviors diff

            //just always hang at await Database.HashGetAllAsync(this.DaemonStatusHashKeyName);
            //1st try
            //telemetrydata = svc.GetAllDaemonStatusListAsync().Result;

            //2nd try
            //var datatask = svc.GetAllDaemonStatusListAsync();
            //datatask.Wait();
            //telemetrydata = datatask.Result; 


            return PartialView("_DaemonStatusResult",telemetrydata);
        }
    }
}

src/Angiris.CentralAdmin.WebApp/Controllers/HomeController.cs
using Angiris.CentralAdmin.Core;
using Angiris.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Angiris.CentralAdmin.WebApp.Controllers
{
    public class HomeController : Controller
    {


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


    }
}

src/Angiris.CentralAdmin.WebApp/Controllers/ScheduledTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Angiris.CentralAdmin.Core;
using Microsoft.AspNet.SignalR;


namespace Angiris.CentralAdmin.WebApp.Controllers
{
    public class ScheduledTaskController : Controller
    {
        // GET: ScheduledTask
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult _GenerateTasks(int taskCount)
        {
            ScheduledFlightCrawlRequestFactory flightCrawlRequestFactory = new ScheduledFlightCrawlRequestFactory();
             
            var task = Task.Run(async () =>
            {
                try
                {
                    await flightCrawlRequestFactory.StartPushTaskMessages(taskCount, BroadcastPushTaskUpdate);
                }
                catch (Exception ex)
                {
                    BroadcastPushTaskUpdate(ex.Message + System.Environment.NewLine + ex.InnerException.Message);
                }

            });
            //task.Wait();
            return View();
        }

        private static readonly IHubContext HubContext = GlobalHost.ConnectionManager.GetHubContext<CrawlResultHub>();

        private void BroadcastPushTaskUpdate(string msg)
        {
            Task.Run(() =>
            {
                HubContext.Clients.All.addNewMessage(msg);
            });
        }
    }
}

src/Angiris.CentralAdmin.WebApp/Views/Console/FlightQuery.cshtml
@{
    ViewBag.Title = "Flight Query";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using System.Collections
@using System.Web.Mvc.Html
@using Angiris.Core.Models
<h2>flightquery</h2>

@using (Ajax.BeginForm("_FlightQuery", "Console", new { },
                new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "ResponseDataPanel",OnBegin = "StartLoading()",OnComplete = "EndLoading()"}
                ))
{

    <div class="row">
        <div class="col-md-3">
            departure:@Html.DropDownList("departure", 
            FakeFlightDataSource.CityNameList.Select(c => new SelectListItem() { Text = c, Value = c }),
                new { id = "departure" })
        </div>
        <div class="col-md-3">
            arrival:@Html.DropDownList("arrival", FakeFlightDataSource.CityNameList.Select(c => new SelectListItem() { Text = c, Value = c }),
                new { id = "arrival" })
        </div>
        <div class="col-md-3">
            date:
            @*@Html.TextBox("date")*@
           
            @Html.DropDownList("date", new List<SelectListItem>(), new { id = "date", style="width:100px;" })
             
        </div>
        <div class="col-md-3">

            @{
    List<SelectListItem> companylist = FakeFlightDataSource.CompanyNameList.Select(c => new SelectListItem() { Text = c, Value = c }).ToList();
    companylist.Insert(0, new SelectListItem() { Text = "N/A", Value = "" });
            }

            company:@Html.DropDownList("company", companylist)
        </div>

    </div>
    <div class="row">
        <div class="col-md-2">
            <input type="submit" value="Query" class="btn btn-default"/>
        </div>
        <div class="col-md-2" id="loading">
            <p>loading...</p>
        </div>
    </div>
 
    <div id="ResponseDataPanel">

    </div>

}
 

@section scripts
{
    <script type="text/javascript">
        $(function() {
            EndLoading();

            $("#departure").change(function () { UpdateDatetimeList() });
            $("#arrival").change(function () { UpdateDatetimeList() });

            UpdateDatetimeList();
        });

        function StartLoading() {
            $('#loading').fadeIn();
        }

        function EndLoading() {
            $('#loading').fadeOut();
        }

        function UpdateDatetimeList() {

            var dateSel = $("#date");

            dateSel.empty();
            $("<option>Loading...</option>").appendTo("#date");
            
            var departure = $("#departure").val();
            var arrival = $("#arrival").val();

            var jsonUrl = "/Console/ListDates?departure=" + departure + "&arrival=" + arrival;
            $.getJSON(jsonUrl, function(data) {

                dateSel.empty();

                if (data.length > 0) {
                    $.each(data, function (key, val) {

                        $("<option value='" + val + "'>" + val + "</option>").appendTo("#date");

                    });
                } else {
                    $("<option>N/A</option>").appendTo("#date");
                }




            });

           

        }
    </script>

}

src/Angiris.CentralAdmin.WebApp/Views/Console/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 


 

src/Angiris.CentralAdmin.WebApp/Views/Console/_FlightQueryResult.cshtml
@model IEnumerable<Angiris.Core.Models.FlightResponse>
<table class="table table-hover table-striped">
    <tr>
        <th>Company</th>
        <th>FlightNumber</th>
        <th>FlightDate</th>
        <th>DepartureCity</th>
        <th>DepartureTime</th>
        <th>ArrivalCity</th>
        <th>ArrivalTime</th>
        <th>TimeStamp</th>
    </tr>
    @foreach (var resp in Model)
    {
        <tr>
            <td>@resp.Company</td>
            <td>@resp.FlightNumber</td>
            <td>@resp.FlightDate.Date.ToString("M/d/yyyy dddd")</td>
            <td>@resp.DepartureCity</td>
            <td>@resp.DepartureTime.Date.ToString("t")</td>
            <td>@resp.ArrivalCity</td>
            <td>@resp.ArrivalTime.Date.ToString("g")</td>
            <td>@resp.TimeStamp</td>
        </tr>
        <tr>
            <td colspan="8">
                <table class="table table-hover table-striped table-bordered table-condensed">
                    <tr>
                        <th>
                            Cabin
                        </th>
                        <th>
                            Total
                        </th>
                        <th>
                            CabinPrice
                        </th>
                        <th>
                            AirPortFee
                        </th>
                        <th>
                            FuelFee
                        </th>
                        <th>
                            Insurance
                        </th>
                        <th>
                            OtherFee
                        </th>
                    </tr>
                    @foreach (var cabin in resp.FlightCabins)
                    {
                        <tr>
                            <td>
                                @cabin.CabinName
                            </td>
                            <td>
                                @cabin.CurrencyType &nbsp;
                                @cabin.TotalPrice
                            </td>
                            <td>
                                @cabin.CabinPrice
                            </td>
                            <td>
                                 @cabin.AirPortFee
                            </td>
                            <td>
                                 @cabin.FuelFee
                            </td>
                            <td>
                                 @cabin.InsuranceName &nbsp;
                                @cabin.InsurancePrice
                            </td>
                            <td>
                                 @cabin.OtherFee
                            </td>
                        </tr>
                    }
                </table>
            </td>
        </tr>
    }
</table>

src/Angiris.CentralAdmin.WebApp/Views/Dashboard/DaemonStatus.cshtml
@{
    ViewBag.Title = "Daemon Status Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>DaemonStatus</h2>

@*<h1><img src="../../img/layout-brand-sm.png" style="margin-left:4px;" /><br />Daemon Status</h1>*@
@*<div ng-controller="sbAppController">

    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4">
                Instance Name: @item.InstanceName <br />
                <span style="font-size: 3.5em;">{{sender.rate}}</span> <br />
                <span style="font-size: 1em;">msgs/sec</span>
            </div>

            <div class="col-md-8">
                Instance Status: <span style="font-weight: bold;"></span>
                <div class="row">
                    <div class="col-md-2">
                        <span style="font-size: 3.5em;">Memory Ratio: @item.MemoryRatio</span> <br />
                        <span style="font-size: 3.5em;">CPU Ratio: @item.CPURatio</span> <br />
                        <span style="font-size: 3.5em;">Network Ratio: @item.NetworRatio</span><br />
                    </div>
                </div>
            </div>
        }
    </div>
</div>*@


<div id="DaemonStatusResult">
    @*@{
        Html.RenderPartial("_DaemonStatusResult");
    }*@
</div>

@section scripts
{
    <script type="text/javascript">
        
        $(function () {
              
            var url = "@(Html.Raw(Url.Action("_DaemonStatusResult", "Dashboard")))";
            $("#DaemonStatusResult").load(url);
            setInterval(function () {
                var url = "@(Html.Raw(Url.Action("_DaemonStatusResult", "Dashboard")))";
                $("#DaemonStatusResult").load(url);
            }, 2000); //Refreshes every 2 seconds

            $.ajaxSetup({ cache: false });
        });

    </script>
}

src/Angiris.CentralAdmin.WebApp/Views/Dashboard/_DaemonStatusResult.cshtml
@model  List<Angiris.Core.Models.DaemonStatus>
     
<ul class="list-inline" style="font-family: Segoe UI Light; font-size: 13px;">
    @foreach (var daemonStatus in Model)
    {
        <li style="margin-top: 5px;">
            @Html.Raw(daemonStatus.ToString().Replace("\r\n", "<br />"))
        </li>
    }
</ul>

src/Angiris.CentralAdmin.WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/Angiris.CentralAdmin.WebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    999 Zixing Rd, Shanghai<br />
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:me@ranger.im">me@ranger.im</a><br />
    <strong>Github:</strong>   <a  href="https://github.com/rangeryu">rangeryu</a>
</address>

src/Angiris.CentralAdmin.WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>What's Project Angiris</h1>
    <p>
        Proof-Of-Concept of Backend(Crawler)-as-a-Service (BaaS) on Azure
    </p>
    <p>
        ● Crawling external resources on-demand or by schedule with pre-defined logics and rules
    </p>
    <p>
        ● Storing and indexing entities in NoSQL database
    </p>
    <p>
        ● A distributed Azure solution with high scalability & availability
    </p>
    <p>
        ● Hosting an agent farm to handle extensible crawlers and query-tasks asynchronously
    </p>


    <p><a class="btn btn-default" href="https://github.com/rangeryu">Learn more &raquo;</a>
    </p>

    <p>
        API Management Dev portal: <a href="https://angirisdemo.portal.azure-api.net" target="_blank">https://angirisdemo.portal.azure-api.net</a>
    </p>
</div>

<div class="row">

    <div class="col-md-6 ">
        <img class="img-responsive" src="~/Images/Overview.PNG" />
    </div>
    <div class="col-md-6 ">
        <img class="img-responsive"  src="~/Images/SlnArch.PNG" />
    </div>
 
</div>

src/Angiris.CentralAdmin.WebApp/Views/ScheduledTask/Index.cshtml
@{
    ViewBag.Title = "Crawl Tasks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div >

    <h2>Mocking FlightCrawlRequestFactory.StartPushTaskMessages</h2>

    @using (Ajax.BeginForm("_GenerateTasks", "ScheduledTask", new { },
    new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "ResponseDataPanel", OnBegin = "StartLoading()", OnComplete = "EndLoading()" }
    ))
    {
        <div class="row">
            <div class="col-md-3">
               TaskCount: @Html.DropDownList("taskCount",(new string[] {"10","100","300"}).Select(c=>new SelectListItem(){Text=c,Value = c}))
            </div>
            <div class="col-md-3">
                <input id="startbutton" type="submit" value="Start" class="btn btn-default"/>
                <span onclick="ClearLog()" class="btn btn-default">Clear Log</span>
            </div>
            <div class="col-md-3" id="loading">
                <p>loading...</p>
            </div>
        </div>

    }
    <div id="ResponseDataPanel">
        
    </div>
    <ul id="msgList"></ul>

</div>

@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {

            EndLoading();
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.crawlResultHub;
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessage = function (message) {
                // Add the message to the page.
                $('#msgList').append('<li><strong>' + (new Date()).toLocaleTimeString()
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            // Start the connection.
            $.connection.hub.start();
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<p />').text(value).html();
            return encodedValue;
        }

        function StartLoading() {
            $('#loading').fadeIn();
        }

        function EndLoading() {
            $('#loading').fadeOut();
        }

        function ClearLog() {
            $('#msgList').empty();
        }
    </script>
}

src/Angiris.CentralAdmin.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Angiris.CentralAdmin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link rel="stylesheet" href="../../css/qunit-git.css" type="text/css" />
    <link rel="stylesheet" href="../../css/main.css" type="text/css" />
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"> </script>

    <script src="../../Scripts/servicebussdk-1.0.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <!--<script src="Scripts/servicebusjssdk-1.0.min.js"></script>-->
    <!-- Syntax Highlighter -->
    <link rel="stylesheet" href="../../css/shCore.css" type="text/css" /> <!-- SyntaxHighlighter CSS style -->
    <link rel="stylesheet" href="../../css/shThemeEclipse.css" type="text/css" /> <!-- SyntaxHighlighter ThemeStyle -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <script type="text/javascript" src="../../Scripts/angular.js"></script>

    <script type="text/javascript" src="../../Scripts/Keys.js"></script>
    <script type="text/javascript" src="../../Scripts/code.js"></script>*@

    <!-- Syntax Highlighter -->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Project Angiris", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Console", "Index", "Console")</li>
                    <li>@Html.ActionLink("Dashboard", "DaemonStatus", "Dashboard")</li>
                    <li>@Html.ActionLink("Scheduled Task", "Index", "ScheduledTask")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Central Admin - Project Angiris</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/unobtrusive")
    @RenderSection("scripts", required: false)
</body>
</html>